#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# source zsh file in customs directory
if [[ -d "${ZDOTDIR:-$HOME}/.zprezto/customs/" ]]; then
  for file in ${ZDOTDIR:-$HOME}/.zprezto/customs/*
  do
    source $file
  done
fi

eval "$(rbenv init -)"
